version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - NODE_ENV=production
    volumes:
      - ./ui:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend 